services:
  ai-file-reader-backend:
    build:
      context: ./AI File Reader/backend
    container_name: ai-file-reader-backend
    ports:
      - "5000:5000"
    volumes:
      - ./AI File Reader/backend:/usr/src/app
    env_file:
      - ./AI File Reader/backend/.env
    dns:
      - 8.8.8.8
      - 8.8.8.4
    environment:
      - QDRANT_URL=http://vector-db:6333
    depends_on:
      - vector-db

  ai-file-reader-frontend:
    build:
      context: ./AI File Reader/frontend
    container_name: ai-file-reader-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./AI File Reader/frontend:/usr/src/app
      - /usr/src/app/node_modules

  nodejs:
    image: node:22-alpine
    container_name: nodejs
    command: sleep infinity
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_storage: